build(ci): added CI runners hardening (#4054)
* added CI runners hardening

Signed-off-by: Francisco Vila <fvila@redhat.com>

* fix ? character added by mistake

Signed-off-by: Francisco Vila <fvila@redhat.com>

* fix ? character added by mistake

Signed-off-by: Francisco Vila <fvila@redhat.com>

* remove hardening for pr

Signed-off-by: Francisco Vila <fvila@redhat.com>

* remove hardening for pr

Signed-off-by: Francisco Vila <fvila@redhat.com>

* remove hardening for pr

Signed-off-by: Francisco Vila <fvila@redhat.com>

* remove audit from documentation tests

Signed-off-by: Francisco Vila <fvila@redhat.com>

* try to add audit to some jobs

Signed-off-by: Francisco Vila <fvila@redhat.com>

---------

Signed-off-by: Francisco Vila <fvila@redhat.com>

diff --git a/.github/workflows/integration-tests.yaml b/.github/workflows/integration-tests.yaml
--- a/.github/workflows/integration-tests.yaml
+++ b/.github/workflows/integration-tests.yaml
@@ -33,6 +33,11 @@ jobs:
       test_chunks: ${{ steps.discover.outputs.test_chunks }}
       modules: ${{ steps.discover.outputs.modules }}
     steps:
+      - name: Harden the runner (Audit all outbound calls)
+        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
+        with:
+          egress-policy: audit
+
       - name: 'Check out repository'
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
         with:
@@ -70,6 +75,11 @@ jobs:
     outputs:
       kroxylicious_image: ${{ steps.build_image.outputs.KROXYLICIOUS_IMAGE }}
     steps:
+      - name: Harden the runner (Audit all outbound calls)
+        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
+        with:
+          egress-policy: audit
+
       - name: 'Check out repository'
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
         with:
@@ -127,6 +137,11 @@ jobs:
       matrix:
         tests: ${{ fromJson(needs.discover_integration_test_chunks.outputs.test_chunks) }}
     steps:
+      - name: Harden the runner (Audit all outbound calls)
+        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
+        with:
+          egress-policy: audit
+
       - name: Parse test specifications
         id: parse
         run: |
@@ -260,6 +275,11 @@ jobs:
     needs: build_artifacts
     runs-on: ubuntu-latest
     steps:
+      - name: Harden the runner (Audit all outbound calls)
+        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
+        with:
+          egress-policy: audit
+
       - name: 'Check out repository'
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
         with:
@@ -288,19 +308,24 @@ jobs:
     permissions:
       actions: read
     steps:
-    - name: 'Check all matrix builds'
-      env:
-        GH_TOKEN: ${{ github.token }}
-      run: |
-        FAILED_JSON=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
-          --jq '.jobs[] | select(.conclusion=="failure") | {name: .name, url: .html_url}')
-        if [ -z "$FAILED_JSON" ]; then
-          echo "All jobs passed!" >> $GITHUB_STEP_SUMMARY
-          echo "No failures detected."
-          exit 0
-        fi
-        echo "Failed Matrix Jobs" >> $GITHUB_STEP_SUMMARY
-        echo "The following instances failed:"
-        echo "$FAILED_JSON" | jq -r '"* [\(.name)](\(.url))"' >> $GITHUB_STEP_SUMMARY
-        echo "$FAILED_JSON" | jq -r '"\(.name): \(.url)"'
-        exit 1
+      - name: Harden the runner (Audit all outbound calls)
+        uses: step-security/harden-runner@ab7a9404c0f3da075243ca237b5fac12c98deaa5 # v2.19.3
+        with:
+          egress-policy: audit
+
+      - name: 'Check all matrix builds'
+        env:
+          GH_TOKEN: ${{ github.token }}
+        run: |
+          FAILED_JSON=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs \
+            --jq '.jobs[] | select(.conclusion=="failure") | {name: .name, url: .html_url}')
+          if [ -z "$FAILED_JSON" ]; then
+            echo "All jobs passed!" >> $GITHUB_STEP_SUMMARY
+            echo "No failures detected."
+            exit 0
+          fi
+          echo "Failed Matrix Jobs" >> $GITHUB_STEP_SUMMARY
+          echo "The following instances failed:"
+          echo "$FAILED_JSON" | jq -r '"* [\(.name)](\(.url))"' >> $GITHUB_STEP_SUMMARY
+          echo "$FAILED_JSON" | jq -r '"\(.name): \(.url)"'
+          exit 1
